# Generated by Django 3.1.2 on 2020-10-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
