# Generated by Django 3.1.2 on 2020-10-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_travel_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='user',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='destination',
            new_name='trip',
        ),
    ]
