# Generated by Django 3.1.2 on 2020-10-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20201027_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='approved',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=8),
        ),
    ]
