# Generated by Django 3.1.2 on 2020-10-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20201027_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='approved',
            new_name='status',
        ),
    ]
